import crypto from "node:crypto";
import { createRequire } from "node:module";
import process from "node:process";
import cookieSession from "cookie-session";
// eslint-ignore import/order
const require = createRequire(import.meta.url);
const package_ = require("../package.json");

export const defaultConfig = {
  application: {
    _devMode: false,
    endpoints: [],
    hasDatabase: false,
    localesAvailable: [
      "de",
      "en",
      "es",
      "es-419",
      "fr",
      "id",
      "nl",
      "pl",
      "pt",
      "sr",
      "zh-Hans-CN",
    ],
    mongodbUrl: process.env.MONGO_URL || false,
    name: "Indiekit",
    port: process.env.PORT || "3000",
    repository: package_.repository,
    themeColor: "#04f",
    themeColorScheme: "automatic",
    timeZone: "UTC",
    ttl: 604_800, // 7 days
    version: package_.version,
  },
  plugins: [
    "@indiekit/endpoint-auth",
    "@indiekit/endpoint-files",
    "@indiekit/endpoint-image",
    "@indiekit/endpoint-media",
    "@indiekit/endpoint-micropub",
    "@indiekit/endpoint-posts",
    "@indiekit/endpoint-share",
    "@indiekit/endpoint-syndicate",
  ],
  publication: {
    categories: [],
    locale: "en",
    me: undefined,
    postTemplate: undefined,
    postTypes: [
      {
        type: "article",
        name: "Article",
        h: "entry",
        properties: [
          "category",
          "content",
          "geo",
          "mp-slug",
          "mp-syndicate-to",
          "name",
          "post-status",
          "published",
          "summary",
          "visibility",
        ],
        "required-properties": ["content", "name", "published"],
      },
      {
        type: "note",
        name: "Note",
        h: "entry",
        properties: [
          "category",
          "content",
          "geo",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "visibility",
        ],
        "required-properties": ["content", "published"],
      },
      {
        type: "photo",
        name: "Photo",
        h: "entry",
        properties: [
          "category",
          "content",
          "geo",
          "mp-photo-alt",
          "mp-slug",
          "mp-syndicate-to",
          "photo",
          "post-status",
          "published",
          "visibility",
        ],
        "required-properties": ["photo", "published", "mp-photo-alt"],
      },
      {
        type: "video",
        name: "Video",
        h: "entry",
        properties: [
          "category",
          "content",
          "geo",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "video",
          "visibility",
        ],
        "required-properties": ["video", "published"],
      },
      {
        type: "audio",
        name: "Audio",
        h: "entry",
        properties: [
          "audio",
          "category",
          "content",
          "geo",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "visibility",
        ],
        "required-properties": ["audio", "published"],
      },
      {
        type: "bookmark",
        name: "Bookmark",
        h: "entry",
        properties: [
          "bookmark-of",
          "category",
          "content",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "visibility",
        ],
        "required-properties": ["bookmark-of", "published"],
      },
      {
        type: "event",
        name: "Event",
        h: "event",
        properties: [
          "category",
          "content",
          "end",
          "name",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "start",
          "url",
          "visibility",
        ],
        "required-properties": ["name", "start", "published"],
      },
      {
        type: "rsvp",
        name: "RSVP",
        h: "entry",
        properties: [
          "in-reply-to",
          "category",
          "content",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "rsvp",
          "visibility",
        ],
        "required-properties": ["rsvp", "in-reply-to", "published"],
      },
      {
        type: "reply",
        name: "Reply",
        h: "entry",
        properties: [
          "in-reply-to",
          "category",
          "content",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "visibility",
        ],
        "required-properties": ["content", "in-reply-to", "published"],
      },
      {
        type: "repost",
        name: "Repost",
        h: "entry",
        properties: [
          "category",
          "content",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "repost-of",
          "visibility",
        ],
        "required-properties": ["repost-of", "published"],
      },
      {
        type: "like",
        name: "Like",
        h: "entry",
        properties: [
          "category",
          "content",
          "like-of",
          "mp-slug",
          "mp-syndicate-to",
          "post-status",
          "published",
          "visibility",
        ],
        "required-properties": ["like-of", "published"],
      },
    ],
    preset: undefined,
    slugSeparator: "-",
    storeMessageTemplate: (metaData) =>
      `${metaData.action} ${metaData.postType} ${metaData.fileType}`,
    syndicationTargets: [],
  },
};

defaultConfig.application.sessionMiddleware = cookieSession({
  name: defaultConfig.application.name,
  secret: crypto.randomBytes(16).toString(),
});
